CREATE TABLE org (
  pk SERIAL PRIMARY KEY,
  id TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE account (
  pk SERIAL PRIMARY KEY,
  id TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE org_account (
  pk SERIAL PRIMARY KEY,
  org_pk INTEGER NOT NULL REFERENCES org(pk),
  account_pk INTEGER NOT NULL REFERENCES account(pk),
  CONSTRAINT org_account_unique UNIQUE (org_pk, account_pk),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE account_log (
  pk SERIAL PRIMARY KEY,
  tag TEXT NOT NULL,
  time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  data JSONB NOT NULL
);
